# Site settings
title: "DNDIY"
email: dndiy@dndiy.org
description: "A series of bad DIY projects"
baseurl: ""
url: "http://dndiy.org"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: false
